Vagrant.configure("2") do |config|
#ansible_controller-1
  config.vm.define "ansible_controller" do |controller|
  config.vm.hostname = "controller-1"
  config.vm.network :private_network, ip: "192.168.254.128", netmask: "255.255.255.0"
  end
  config.vm.box = "bento/debian-8.3"
  config.vm.provider :vmware_workstation do |v|
    v.gui = true
    v.vmx["displayName"] = "ansible_controller-1"
    v.vmx["numvcpus"] = "2"
    v.vmx["memsize"] = "3125"
    v.vmx["ethernet0.wakeonpcktrcv"] = "FALSE"
  end
#node-1
  config.vm.define "node-1" do |node|
  config.vm.hostname = "node-1"
  config.vm.network :private_network, ip: "192.168.254.129", netmask: "255.255.255.0"
  end
  config.vm.box = "bento/debian-8.3"
  config.vm.provider :vmware_workstation do |v|
    v.gui = false
    v.vmx["displayName"] = "node-1"
    v.vmx["numvcpus"] = "1"
    v.vmx["memsize"] = "256"
    v.vmx["ethernet0.wakeonpcktrcv"] = "FALSE"
  end
#node-2
  config.vm.define "node-2" do |node|
  config.vm.hostname = "node-2"
  config.vm.network :private_network, ip: "192.168.254.130", netmask: "255.255.255.0"
  end
  config.vm.box = "bento/debian-8.3"
  config.vm.provider :vmware_workstation do |v|
    v.gui = false
    v.vmx["displayName"] = "node-2"
    v.vmx["numvcpus"] = "1"
    v.vmx["memsize"] = "256"
    v.vmx["ethernet0.wakeonpcktrcv"] = "FALSE"
  end
#node-3
  config.vm.define "node-3" do |node|
  config.vm.hostname = "node-3"
  config.vm.network :private_network, ip: "192.168.254.131", netmask: "255.255.255.0"
  end
  config.vm.box = "bento/debian-8.3"
  config.vm.provider :vmware_workstation do |v|
    v.gui = false
    v.vmx["displayName"] = "node-3"
    v.vmx["numvcpus"] = "1"
    v.vmx["memsize"] = "256"
    v.vmx["ethernet0.wakeonpcktrcv"] = "FALSE"
  end
#node-4
  config.vm.define "node-4" do |node|
  config.vm.hostname = "node-4"
  config.vm.network :private_network, ip: "192.168.254.132", netmask: "255.255.255.0"
  end
  config.vm.box = "bento/debian-8.3"
  config.vm.provider :vmware_workstation do |v|
    v.gui = false
    v.vmx["displayName"] = "node-4"
    v.vmx["numvcpus"] = "1"
    v.vmx["memsize"] = "256"
    v.vmx["ethernet0.wakeonpcktrcv"] = "FALSE"
  end
end
